<?php
$theme = $this->helper('skstore');
$newsLetter = $theme->getCfg('magento_blocks/footer_newsletter');
?>
<?php if($newsLetter):?>
<div class="subscribe">
    <h3><span><?php echo $this->__('Newsletter') ?></span></h3>
    <form action="<?php echo $this->getFormActionUrl() ?>" method="post" id="newsletter-validate-detail">
        <div class="block-content">
            <div class="form-subscribe-header">
                <span><?php echo $this->__('Subscribe to receive updates on new arrivals, special offers and other discount.') ?></span>
            </div>
            <div class="input-box">
                <input name="email" type="text" id="newsletter" value="<?php echo $this->__('Your Email...') ?>" onclick="this.value=='<?php echo $this->__('Your Email...') ?>'?this.value='':''" onblur="this.value==''?this.value='<?php echo $this->__('Your Email...') ?>':''"  class="input-text required-entry validate-email" />
            </div>
            <div class="actions h4">
                <button type="submit" title="<?php echo $this->__('Submit') ?>" class="button"><?php echo $this->__('Submit') ?></button>
            </div>
        </div>
    </form>
    <script type="text/javascript">
    //<![CDATA[
        var newsletterSubscriberFormDetail = new VarienForm('newsletter-validate-detail');
    //]]>
    </script>
</div>
<?php endif;?>
