<?php 
	$_helper    = $this->helper('catalog/output');
    $_category  = $this->getCurrentCategory();

?>
<?php if($_description=$this->getCurrentCategory()->getDescription()): ?>
<div class="category-description clearfix">
    <div class="category-description std">
        <?php echo $_helper->categoryAttribute($_category, $_description, 'description') ?>
    </div>
</div>
<?php elseif ($this->getChildHtml("category_top_block")) : ?>
<div class="category-top-block std">
	<?php echo  $this->getChildHtml("category_top_block"); ?>
</div>
<?php endif ?>