<?php
$_helper    = $this->helper('catalog/output');
$_category  = $this->getCurrentCategory();
?>
<div class="category-top">
	<div class="page-title category-title">
		<?php if($this->IsRssCatalogEnable() && $this->IsTopCategory()): ?>
			<a href="<?php echo $this->getRssLink() ?>" class="link-rss"><?php echo $this->__('Subscribe to RSS Feed') ?></a>
		<?php endif; ?>
		<h1><?php echo $_helper->categoryAttribute($_category, $_category->getName(), 'name') ?></h1>
	</div>
</div>
