<?php
/**
 * @copyright    Copyright (C) 2015 Skstore. All Rights Reserved.
 */
?>
<!-- navigation BOF -->
<div class="block block-nav">
    <div class="block-title">
        <strong><span><?php echo $this->__('Categories'); ?></span></strong>
    </div>
    <div class="block-content">
        <ul id="categories-nav" class="nav-accordion nav-categories">
            <?php echo $this->renderCategoriesMenuHtml(TRUE, TRUE, 0, 'level-top'); ?>
        </ul>
        <script type="text/javascript">
            $ktm(document).ready(function() {
                $ktm("#categories-nav").KtmAccordion({
                    accordion:true,
                    speed: 400,
                    closedSign: 'collapse icon_plus',
                    openedSign: 'expand icon_minus-06',
                    mouseType: 0,
                    easing: 'easeInOutQuad'
                });
				$ktm(".expand").empty();
            });
        </script>
    </div>
</div>
<!-- navigation EOF -->