<?php
/**
 * @copyright    Copyright (C) 2015 Skstore. All Rights Reserved.
 */
?>
<?php
    $bar = Mage::helper('ktmcorefilter')->getConfig('ktmcorefilter/general/bar');
?>
<div id="<?php echo $this->getHash()?>" class="price-slider">
    <div id="<?php echo $this->getHash('-min')?>" class="price-slider-handle min"></div>
    <div id="<?php echo $this->getHash('-max')?>" class="price-slider-handle max"></div>
    <div id="<?php echo $this->getHash('-span')?>" class="price-slider-span"></div>
</div>
<div class="layer-price">
    <?php echo $this->getCurrencySymbol()?><span id="layer-price-min"></span>&nbsp;&nbsp;-&nbsp;&nbsp;<?php echo $this->getCurrencySymbol()?><span id="layer-price-max"></span>
</div>
<script type="text/javascript">
    window.ktmcoreFilter.initPriceFilter(<?php echo $this->getConfig()?>);
</script>