<?php
    $helper = Mage::helper('ktmwidget');
    $posts = $this->getPosts();
?>
<div id="messages_product_view">
<?php
    Mage::app()->getLayout()->getMessagesBlock()->setMessages(Mage::getSingleton('customer/session')->getMessages(true));
    echo Mage::app()->getLayout()->getMessagesBlock()->getGroupedHtml();
?>
</div>


<div class="postWrapper-blog-standard clearfix">
<?php
//start foreach posts
$countPost = 0;
foreach ($posts as $post):
$countPost++;
?>
        <div class= "postContent-blog2 col-md-6 <?php if($countPost %2 !== 0) {echo 'no-padding-left clearfix';}else {echo 'no-padding-right';} ?> pb-20">
                <div class="col-md-12">
                    <?php
                    $img = $helper->getImgBlog($post->getShortContent());
                    if ($img):
                    ?>
                        <a href="<?php echo $post->getAddress(); ?>" alt="<?php echo $post->getTitle(); ?>" title="<?php echo $post->getTitle(); ?>"/>
                            <div class="image-blog2" style="background-image: url(<?php echo $img; ?>)"></div>
                        </a>
                    <?php 
                    endif;
                    ?>
                </div>
                <div class="col-md-12">
                        <h2><a href="<?php echo $post->getAddress(); ?>" >
                            <?php echo $post->getTitle(); ?>
                            </a>
                        </h2>
                        <p>
                        <?php
                            $previousTimeStamp = strtotime($post->getCreatedTime());
                            echo $this->timeShowing($previousTimeStamp);
                        ?>
                        </p>
                        <p class="postContent">
                        <?php
                            $content = $helper->truncate(strip_tags($post->getShortContent()), $length = 160, $etc = '...');
                            echo $content;
                        ?>
                        </p>
                </div>
        </div>
<?php endforeach; ?>
</div>

<?php //echo $this->getChildHtml('aw_blog_comments_toolbar'); ?>