<?php
/**
 * @copyright    Copyright (C) 2015 Skstore. All Rights Reserved.
 */
?>
<div class="ktmcore-socialconnect-register">   
    <div class="<?php echo $this->_getColSet(); ?>">
        <?php if($this->_googleEnabled()): ?>
        <div class="<?php echo $this->_getCol(); ?> ktmcore-socialconnect-register-google">
            <div class="fieldset">
                <h2 class="legend"><?php echo $this->__('Google Connect') ?></h2>
                <p><?php echo $this->__('You can register using your Google account.') ?></p>
                <p><?php echo $this->getChildHtml('ktmcore_socialconnect_checkout_google_button')?></p>
            </div>
        </div>
        <?php endif; ?>
        <?php if($this->_facebookEnabled()): ?>
        <div class="<?php echo $this->_getCol(); ?> ktmcore-socialconnect-register-facebook">
            <div class="fieldset">
                <h2 class="legend"><?php echo $this->__('Facebook Connect') ?></h2>
                <p><?php echo $this->__('You can register using your Facebook account.') ?></p>
                <p><?php echo $this->getChildHtml('ktmcore_socialconnect_checkout_facebook_button')?></p>
            </div>
        </div>
        <?php endif; ?>
        <?php if($this->_twitterEnabled()): ?>
        <div class="<?php echo $this->_getCol(); ?> ktmcore-socialconnect-register-twitter">
            <div class="fieldset">
                <h2 class="legend"><?php echo $this->__('Twitter Connect') ?></h2>
                <p><?php echo $this->__('You can register using your Twitter account.') ?></p>
                <p><?php echo $this->getChildHtml('ktmcore_socialconnect_checkout_twitter_button')?></p>
            </div>
        </div>
        <?php endif; ?>
    </div>
</div>