<?php
/**
 * @copyright    Copyright (C) 2015 Skstore. All Rights Reserved.
 */
?>
<?php
$installer = $this;
$installer->startSetup();

$installer->addAttribute('catalog_category', 'ktmmenu_is_category', array(
    'group'             => 'Ultra Menu',
    'label'             => 'Display in menu',
    'note'              => "Display category in menu. This field is applicable only for top-level categories.",
    'type'              => 'varchar',
    'input'             => 'select',
    'source'            => 'ktmmenu/system_config_source_category_attribute_source_block_display',
    'visible'           => true,
    'required'          => false,
    'backend'           => '',
    'frontend'          => '',
    'searchable'        => false,
    'filterable'        => false,
    'comparable'        => false,
    'user_defined'      => true,
    'visible_on_front'  => true,
    'wysiwyg_enabled'   => false,
    'is_html_allowed_on_front'  => false,
    'global'            => Mage_Catalog_Model_Resource_Eav_Attribute::SCOPE_STORE,
));

$installer->addAttribute('catalog_category', 'ktmmenu_cat_groups', array(
    'group'             => 'Ultra Menu',
    'label'             => 'Category Menu Type',
    'note'              => "Show subcategories by. This field is applicable only for top-level categories.",
    'type'              => 'varchar',
    'input'             => 'select',
    'source'            => 'ktmmenu/system_config_source_category_attribute_source_block_types',
    'visible'           => true,
    'required'          => false,
    'backend'           => '',
    'frontend'          => '',
    'searchable'        => false,
    'filterable'        => false,
    'comparable'        => false,
    'user_defined'      => true,
    'visible_on_front'  => true,
    'wysiwyg_enabled'   => false,
    'is_html_allowed_on_front'  => false,
    'global'            => Mage_Catalog_Model_Resource_Eav_Attribute::SCOPE_STORE,
));

$installer->addAttribute('catalog_category', 'ktmmenu_is_alignment', array(
    'group'             => 'Ultra Menu',
    'label'             => 'Alignment',
    'note'              => "Align submenu.",
    'type'              => 'varchar',
    'input'             => 'select',
    'source'            => 'ktmmenu/system_config_source_category_attribute_source_align_align',
    'visible'           => true,
    'required'          => false,
    'backend'           => '',
    'frontend'          => '',
    'searchable'        => false,
    'filterable'        => false,
    'comparable'        => false,
    'user_defined'      => true,
    'visible_on_front'  => true,
    'wysiwyg_enabled'   => false,
    'is_html_allowed_on_front'  => false,
    'global'            => Mage_Catalog_Model_Resource_Eav_Attribute::SCOPE_STORE,
));

$installer->addAttribute('catalog_category', 'ktmmenu_is_width', array(
    'group'             => 'Ultra Menu',
    'label'             => 'Width',
    'note'              => "Submenu width.",
    'type'              => 'text',
    'input'             => 'text',
    'visible'           => true,
    'required'          => false,
    'backend'           => '',
    'frontend'          => '',
    'searchable'        => false,
    'filterable'        => false,
    'comparable'        => false,
    'user_defined'      => true,
    'visible_on_front'  => true,
    'wysiwyg_enabled'   => true,
    'is_html_allowed_on_front'  => true,
    'global'            => Mage_Catalog_Model_Resource_Eav_Attribute::SCOPE_STORE,
));

$installer->addAttribute('catalog_category', 'ktmmenu_proportions_left', array(
    'group'             => 'Ultra Menu',
    'label'             => 'Proportions: Block Left',
    'note'              => "Proportions block Block Left. This field is applicable only for top-level categories.",
    'type'              => 'varchar',
    'input'             => 'select',
    'source'            => 'ktmmenu/system_config_source_category_attribute_source_block_proportions',
    'visible'           => true,
    'required'          => false,
    'backend'           => '',
    'frontend'          => '',
    'searchable'        => false,
    'filterable'        => false,
    'comparable'        => false,
    'user_defined'      => true,
    'visible_on_front'  => true,
    'wysiwyg_enabled'   => false,
    'is_html_allowed_on_front'  => false,
    'global'            => Mage_Catalog_Model_Resource_Eav_Attribute::SCOPE_STORE,
));

$installer->addAttribute('catalog_category', 'ktmmenu_cat_columns', array(
    'group'             => 'Ultra Menu',
    'label'             => 'Categories Columns',
    'note'              => "This field is applicable only for top-level categories.",
    'type'              => 'varchar',
    'input'             => 'select',
    'source'            => 'ktmmenu/system_config_source_category_attribute_source_block_proportions',
    'visible'           => true,
    'required'          => false,
    'backend'           => '',
    'frontend'          => '',
    'searchable'        => false,
    'filterable'        => false,
    'comparable'        => false,
    'user_defined'      => true,
    'visible_on_front'  => true,
    'wysiwyg_enabled'   => false,
    'is_html_allowed_on_front'  => false,
    'global'            => Mage_Catalog_Model_Resource_Eav_Attribute::SCOPE_STORE,
));

$installer->addAttribute('catalog_category', 'ktmmenu_proportions_right', array(
    'group'             => 'Ultra Menu',
    'label'             => 'Proportions: Block Right',
    'note'              => "Proportions block Block Right. This field is applicable only for top-level categories.",
    'type'              => 'varchar',
    'input'             => 'select',
    'source'            => 'ktmmenu/system_config_source_category_attribute_source_block_proportions',
    'visible'           => true,
    'required'          => false,
    'backend'           => '',
    'frontend'          => '',
    'searchable'        => false,
    'filterable'        => false,
    'comparable'        => false,
    'user_defined'      => true,
    'visible_on_front'  => true,
    'wysiwyg_enabled'   => false,
    'is_html_allowed_on_front'  => false,
    'global'            => Mage_Catalog_Model_Resource_Eav_Attribute::SCOPE_STORE,
));

$installer->addAttribute('catalog_category', 'ktmmenu_cat_block_left', array(
    'group'             => 'Ultra Menu',
    'label'             => 'Block Left',
    'note'              => "This field is applicable only for top-level categories.",
    'type'              => 'text',
    'input'             => 'textarea',
    'visible'           => true,
    'required'          => false,
    'backend'           => '',
    'frontend'          => '',
    'searchable'        => false,
    'filterable'        => false,
    'comparable'        => false,
    'user_defined'      => true,
    'visible_on_front'  => true,
    'wysiwyg_enabled'   => true,
    'is_html_allowed_on_front'  => true,
    'global'            => Mage_Catalog_Model_Resource_Eav_Attribute::SCOPE_STORE,
));

$installer->addAttribute('catalog_category', 'ktmmenu_cat_block_right', array(
    'group'             => 'Ultra Menu',
    'label'             => 'Block Right',
    'note'              => "This field is applicable only for top-level categories.",
    'type'              => 'text',
    'input'             => 'textarea',
    'visible'           => true,
    'required'          => false,
    'backend'           => '',
    'frontend'          => '',
    'searchable'        => false,
    'filterable'        => false,
    'comparable'        => false,
    'user_defined'      => true,
    'visible_on_front'  => true,
    'wysiwyg_enabled'   => true,
    'is_html_allowed_on_front'  => true,
    'global'            => Mage_Catalog_Model_Resource_Eav_Attribute::SCOPE_STORE,
));

$installer->addAttribute('catalog_category', 'ktmmenu_cat_block_top', array(
    'group'             => 'Ultra Menu',
    'label'             => 'Block Top',
    'type'              => 'text',
    'input'             => 'textarea',
    'visible'           => true,
    'required'          => false,
    'backend'           => '',
    'frontend'          => '',
    'searchable'        => false,
    'filterable'        => false,
    'comparable'        => false,
    'user_defined'      => true,
    'visible_on_front'  => true,
    'wysiwyg_enabled'   => true,
    'is_html_allowed_on_front'  => true,
    'global'            => Mage_Catalog_Model_Resource_Eav_Attribute::SCOPE_STORE,
));

$installer->addAttribute('catalog_category', 'ktmmenu_cat_block_bottom', array(
    'group'             => 'Ultra Menu',
    'label'             => 'Block Bottom',
    'type'              => 'text',
    'input'             => 'textarea',
    'visible'           => true,
    'required'          => false,
    'backend'           => '',
    'frontend'          => '',
    'searchable'        => false,
    'filterable'        => false,
    'comparable'        => false,
    'user_defined'      => true,
    'visible_on_front'  => true,
    'wysiwyg_enabled'   => true,
    'is_html_allowed_on_front'  => true,
    'global'            => Mage_Catalog_Model_Resource_Eav_Attribute::SCOPE_STORE,
));

$installer->addAttribute('catalog_category', 'ktmmenu_cat_label', array(
    'group'             => 'Ultra Menu',
    'label'             => 'Category Label',
    'note'              => "Labels have to be defined in menu settings",
    'type'              => 'varchar',
    'input'             => 'select',
    'source'            => 'ktmmenu/system_config_source_category_attribute_source_categorylabel',
    'visible'           => true,
    'required'          => false,
    'backend'           => '',
    'frontend'          => '',
    'searchable'        => false,
    'filterable'        => false,
    'comparable'        => false,
    'user_defined'      => true,
    'visible_on_front'  => true,
    'wysiwyg_enabled'   => false,
    'is_html_allowed_on_front'  => false,
    'global'            => Mage_Catalog_Model_Resource_Eav_Attribute::SCOPE_STORE,
));


// $installer->addAttribute('catalog_category', 'ktmmenu_is_vertical', array(
//     'group'             => 'Ultra Menu',
//     'label'             => 'Display in vertical menu',
//     'note'              => "Display category in vertical menu. This field is applicable only for top-level categories.",
//     'type'              => 'varchar',
//     'input'             => 'select',
//     'source'            => 'ktmmenu/system_config_source_category_attribute_source_block_display',
//     'visible'           => true,
//     'required'          => false,
//     'backend'           => '',
//     'frontend'          => '',
//     'searchable'        => false,
//     'filterable'        => false,
//     'comparable'        => false,
//     'user_defined'      => true,
//     'visible_on_front'  => true,
//     'wysiwyg_enabled'   => false,
//     'is_html_allowed_on_front'  => false,
//     'global'            => Mage_Catalog_Model_Resource_Eav_Attribute::SCOPE_STORE,
// ));

// $installer->addAttribute('catalog_category', 'ktmmenu_is_icon', array(
//     'group'             => 'Ultra Menu',
//     'label'             => 'Icon Font',
//     'note'              => "Add icon font to level top menu.",
//     'type'              => 'text',
//     'input'             => 'text',
//     'visible'           => true,
//     'required'          => false,
//     'backend'           => '',
//     'frontend'          => '',
//     'searchable'        => false,
//     'filterable'        => false,
//     'comparable'        => false,
//     'user_defined'      => true,
//     'visible_on_front'  => true,
//     'wysiwyg_enabled'   => false,
//     'is_html_allowed_on_front'  => false,
//     'global'            => Mage_Catalog_Model_Resource_Eav_Attribute::SCOPE_STORE,
// ));

// $installer->addAttribute('catalog_category', 'ktmmenu_is_icon_image', array(
//     'group'             => 'Ultra Menu',
//     'label'             => 'Icon Image',
//     'note'              => "Upload icon image to level top menu.",
//     'type'              => 'text',
//     'input'             => 'image',
//     'visible'           => true,
//     'required'          => false,
//     'backend'           => 'ktmmenu/category_attribute_backend_image',
//     'frontend'          => '',
//     'searchable'        => false,
//     'filterable'        => false,
//     'comparable'        => false,
//     'user_defined'      => true,
//     'visible_on_front'  => true,
//     'wysiwyg_enabled'   => false,
//     'is_html_allowed_on_front'  => false,
//     'global'            => Mage_Catalog_Model_Resource_Eav_Attribute::SCOPE_STORE,
// ));

$installer->endSetup();