<?php
/**
 * @copyright    Copyright (C) 2015 skstore. All Rights Reserved.
 */
?>
<?php
$enable = Mage::getStoreConfig('ajaxcart/ajaxcart_config/enable_ajaxcart');
?>
<?php
$_cartQty = $this->getSummaryCount();
$_items = $this->getRecentItems($_cartQty);
?>
<div class="ktm-cart">
    <div class="ktm-icon-ajaxcart">
        <a class="ktm-cart-label" href="<?php echo $this->getUrl('checkout/cart', Mage::helper('skstore')->checkSSL()) ?>">
            <span class="icon-cart"><i class="icon-basket icons"></i></span>
            <span class="print">
               <span class="items"><?php echo count($_items) ?><?php //echo $this->__('item(s)') ?></span><?php //echo Mage::helper('checkout')->formatPrice($this->getSubtotal()) ?>
            </span>
        </a>
    </div>
    <div class="ajaxcart">
        <div class="search-form-border"></div>
        <div class="ktm-ajax-container">
            <?php
            if (count($_items)):
                ?>
                <ul class="clearfix">
                    <?php foreach ($_items as $_item): ?>
                        <?php echo $this->getItemHtml($_item) ?>
                    <?php endforeach; ?>
                </ul>
                <p class="subtotal">
                    <?php if ($this->canApplyMsrp()): ?>
                        <span
                            class="map-cart-sidebar-total"><?php echo $this->__('ORDER TOTAL WILL BE DISPLAYED BEFORE YOU SUBMIT THE ORDER'); ?></span>
                    <?php else: ?>
                        <span
                            class="label"><?php echo $this->__('Total:') ?></span> <?php echo Mage::helper('checkout')->formatPrice($this->getSubtotal()) ?>
                        <?php if ($_subtotalInclTax = $this->getSubtotalInclTax()): ?>
                            <br/>(<?php echo Mage::helper('checkout')->formatPrice($_subtotalInclTax) ?> <?php echo Mage::helper('tax')->getIncExcText(true) ?>)
                        <?php endif; ?>
                    <?php endif; ?>
                </p>
                <div class="ktm-ajax-checkout">
                    <a href="<?php echo $this->getUrl('checkout/cart', Mage::helper('skstore')->checkSSL()) ?>" class="view-cart">
                        <span><?php echo $this->__('View cart') ?></span>
                    </a>
                    <?php if (Mage::getStoreConfig('opc/global/status')) { ?>
                        <a href="<?php echo $this->getUrl('onepage', Mage::helper('skstore')->checkSSL()) ?>"><span><?php echo $this->__('Checkout') ?></span></a>
                    <?php } else { ?>
                        <a href="<?php echo $this->getCheckoutUrl() ?>"><span><?php echo $this->__('Checkout') ?></span></a>
                    <?php }?>
                </div>
            <?php else: ?>
                <p class="no-items-in-cart"><?php echo $this->__('Shopping cart empty.') ?></p>
            <?php endif ?>
        </div>
    </div>
</div>
<script type="text/javascript">
    var datatext = {};
    datatext.load = '<?php echo $this->__('<i class="fa fa-spinner fa-spin"></i>');?>';
</script>