<?php
/**
 * Bss_Socialfeeds extension
 * 
 * NOTICE OF LICENSE
 * 
 * This source file is subject to the MIT License
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/mit-license.php
 * 
 * @category       Bss
 * @package        Bss_Socialfeeds
 * @copyright      Copyright (c) 2015
 * @license        http://opensource.org/licenses/mit-license.php MIT License
 */
/**
 * Socialfeed view template
 *
 * @category    Bss
 * @package     Bss_Socialfeeds
 * @author      Ultimate Module Creator
 */
?>
<?php $_socialfeed = $this->getCurrentSocialfeed();?>
<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<div class="page-title socialfeed-title">
    <h1><?php echo $_socialfeed->getSocialfeedsStatus(); ?></h1>
</div>
<div class="socialfeed-view">
    <div class="socialfeed-socialfeeds_status">
        <?php echo Mage::helper('bss_socialfeeds')->__('Socialfeeds Status');?>:<?php echo $_socialfeed->getSocialfeedsStatus();?>

    </div>

</div>
