<?php
/**
 * @copyright    Copyright (C) 2015 Skstore. All Rights Reserved.
 */
?>
<div class="clearer">
    <div class="ktmcore-socialconnect-twitter">
        <div class="ktmcore-socialconnect-twitter-inner">
            <a href="<?php echo $this->escapeUrl($this->_getButtonUrl()); ?>"><?php echo $this->_getButtonText(); ?></a>
        </div>
        <div class="ktmcore-socialconnect-twitter-right"></div>
    </div>
</div>
