<?php
/**
 * @copyright    Copyright (C) 2015 Skstore. All Rights Reserved.
 */
?>
<?php
$theme = $this->helper('skstore');
$helpImg = $this->helper('skstore/image');
$imgWidth = $theme->getCfg('category/image_width') ? $theme->getCfg('category/image_width') : 295;
$imgHeight = $theme->getCfg('category/image_height') ? $theme->getCfg('category/image_height') : 295;
if($theme->getCfg('category/aspect_ratio')){
    $imgHeight = 0;
}
$cfaltimage = $theme->getCfg('category/alt_image');
$hoveraltClass = ($cfaltimage == 1) ? 'front-img' : '';
$_helper            = $this->helper('catalog/output');
/* @var $this KtmCore_Widget_Block_Widget_Collection */
$productCollection  = $this->getData('collection');
$count              = $productCollection ? $productCollection->count() : 0;
$carousel           = $this->getData('carousel');
$row                = $this->getData('row');
$pricePrefixId      = $this->getData('price-prefix');
$column             = $carousel == 1 && $row == 1 ? $count : ($carousel == 1 && $row > 1 ? $row : $this->getData('column'));
/* @var $helper Mage_Catalog_Helper_Image */
$helper             = Mage::helper('catalog/image');
?>
<?php if (!$count): ?>
    <p class="note-msg">
        <?php echo $this->__('There are no products matching the selection.') ?>
    </p>
<?php else: ?>
    <?php $i=0; foreach ($productCollection as $_product): ?>
        <?php /* @var $product Mage_Catalog_Model_Product */ ?>
        <?php if ($carousel == 1 && $row > 1 && $i == 0): ?>
            <div class="owl-carousel">
        <?php endif ?>
        <?php if ($i % $column == 0 || ($row > 1 && $i % $row == 0)): ?>
            <ul class="products-grid <?php echo $carousel && $row == 1 ? ' owl-carousel' : '' ?>">
        <?php endif ?>
        <?php $i++ ?>
        <li class="item">
            <div class="item-inner">
                <?php $i++ ?>
                <div class="product-item">
                    <div class="content products-list">
                        <div class="product-hover">
                            <a class="options-cart" href="<?php echo $this->getUrl('ajaxcart/index/options/product_id/' . $_product->getId(), $theme->checkSSL()); ?>" id='options-cart-<?php echo $_product->getId()?>' style='display:none'><?php //echo $this->__('Quickview') ?></a>

                            <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image">

                                <div class="front margin-image">
                                    <img class="img-responsive lazy <?php echo $hoveraltClass;?>"  data-src="<?php echo $helpImg->getImg($_product, $imgWidth, $imgHeight, 'small_image'); ?>" src="<?php echo $this->getSkinUrl('images/loader.gif', $theme->checkSSL()) ?>" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" />
                                </div>
                                <div class="product-img-additional back margin-image">
                                    <?php if ($theme->getCfg('category/alt_image')): ?>
                                        <?php echo $theme->getAltImgHtml($_product, $imgWidth, $imgHeight); ?>
                                    <?php endif; ?>
                                </div>
                            </a>
                        </div>
                    <div class="top-actions-inner">
                        <h3 class="product-name">
                            <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>">
                                <?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?>
                            </a>
                        </h3>
                        <?php echo $this->getReviewsSummaryHtml($_product, 'short') ?>
                        <?php echo $this->getPriceHtml($_product, true, '-'.$pricePrefixId) ?>

                    </div>
                </div>
            </div>
        </li>
        <?php if ($i == $count || $i % $column == 0 || ($row > 1 && $i % $row == 0)): ?>
            </ul>
        <?php endif ?>
        <?php if ($carousel == 1 && $row > 1 && $i == $count): ?>
            </div>
        <?php endif ?>
    <?php endforeach ?>
<?php endif ?>
