<?php
/**
 * @copyright    Copyright (C) 2015 Skstore. All Rights Reserved.
 */
?>
<?php
$theme = $this->helper('skstore');
$helpImg = $this->helper('skstore/image');
$imgWidth = $theme->getCfg('category/image_width') ? $theme->getCfg('category/image_width') : 295;
$imgHeight = $theme->getCfg('category/image_height') ? $theme->getCfg('category/image_height') : 295;
if($theme->getCfg('category/aspect_ratio')){
    $imgHeight = 0;
}
$cfaltimage = $theme->getCfg('category/alt_image');
$hoveraltClass = ($cfaltimage == 1) ? 'front-img' : '';
$_helper            = $this->helper('catalog/output');
/* @var $this KtmCore_Widget_Block_Widget_Collection */
$productCollection  = $this->getData('collection');
$count              = $productCollection ? $productCollection->count() : 0;
$carousel           = $this->getData('carousel');
$row                = $this->getData('row');
$pricePrefixId      = $this->getData('price-prefix');
$column             = $carousel == 1 && $row == 1 ? $count : ($carousel == 1 && $row > 1 ? $row : $this->getData('column'));
/* @var $helper Mage_Catalog_Helper_Image */
$helper             = Mage::helper('catalog/image');
?>
<?php if (!$count): ?>
    <p class="note-msg">
        <?php echo $this->__('There are no products matching the selection.') ?>
    </p>
<?php else: ?>
    <?php $i=0; foreach ($productCollection as $_product): ?>
        <?php if ($carousel == 1 && $row > 1 && $i == 0): ?>
            <div class="owl-carousel owl-theme">
        <?php endif ?>
        <?php if ($i % $column == 0 || ($row > 1 && $i % $row == 0)): ?>
       <div class="category-products collection-position01">
        <ul class="products-grid <?php echo $carousel && $row == 1 ? ' owl-carousel owl-theme' : '' ?>">
    <?php endif ?>
        <?php $i++ ?>
        <li class="item">
            <div class="item-inner">
                <div class="product-item">
                    <div class="content products-list">
                        <div class="product-hover">
                            <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image">
                                <?php echo $this->helper('skstore')->getLabel($_product);  ?>
                                <span class="front margin-image">
                                    <img class="img-responsive owl-lazy <?php echo $hoveraltClass;?>"   data-src="<?php echo $helpImg->getImg($_product, $imgWidth, $imgHeight, 'small_image'); ?>" src="<?php echo $this->getSkinUrl('images/loader.gif', $theme->checkSSL()) ?>" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" />
                                </span>
                                <?php if ($theme->getCfg('category/alt_image')): ?>
                                    <span class="product-img-additional back margin-image">
                                         <?php echo $theme->getAltImgHtml($_product, $imgWidth, $imgHeight); ?>
                                    </span>
                                <?php endif; ?>
                            </a>
                            <div class="product-hover-box">
                                <div class="main-quickview hidden-xs">
                                    <button type="button"  data-placement="top" data-toggle="tooltip" title="<?php echo $this->__('Quick view') ?>" class="button btn-cart show-quickview" data-id="<?php echo $_product->getId(); ?>"><i class="icon-plus"></i></button>
                                    <a class="product-quickview" href="<?php echo $this->getUrl('ajaxcart/index/options/product_id/' . $_product->getId(), $theme->checkSSL()); ?>" data-id='quickview-<?php echo $_product->getId()?>' style='display:none'><?php echo $this->__('Quick view') ?></a>
                                </div>
                                <div class="confix-produclist">
                                    <div class="add-to-links">
                                        <div class="wishlist">
                                            <?php if ($this->helper('wishlist')->isAllow()) : ?>
                                                <a href="<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>" data-id="<?php echo $_product->getId(); ?>" title="<?php echo $this->__('Wishlist') ?>" data-placement="top" data-toggle="tooltip" class="link-wishlist">
                                                    <i class="icon-heart"></i><?php //echo $this->__('Add to Wishlist') ?>
                                                </a>
                                            <?php endif; ?>
                                        </div>
                                        <div class="compare">
                                            <?php if($_compareUrl=$this->getAddToCompareUrl($_product)): ?>
                                                <a href="<?php echo $_compareUrl ?>" data-id="<?php echo $_product->getId(); ?>" title="<?php echo $this->__('Compare') ?>" data-placement="top" data-toggle="tooltip" class="link-compare">
                                                    <i class="icon-chart icons"></i><?php //echo $this->__('Add to Compare') ?>
                                                </a>
                                            <?php endif; ?>
                                        </div>
                                    </div>
                                </div>
                                <div class="ktm-actions clearfix">
                                    <div class="addtocart">
                                        <?php if($_product->isSaleable()): ?>
                                            <?php if ( !($_product->getTypeInstance(true)->hasRequiredOptions($_product) || $_product->isGrouped()) ) { ?>
                                                <button type="button" title="<?php echo $this->__('Add To Cart') ?>" data-placement="top" class="button btn-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')">
                                                    <span>
                                                        <span><?php echo $this->__('Add To Cart') ?></span>
                                                    </span>
                                                </button>
                                            <?php } else { ?>
                                                <button type="button" title="<?php echo $this->__('Add To Cart') ?>" data-placement="top" class="button btn-cart show-options" data-id="<?php echo $_product->getId(); ?>"
                                                    <?php if (!Mage::getStoreConfig('ajaxcart/ajaxcart_config/enable_ajaxcart')) { ?>
                                                        onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"
                                                    <?php }?> data-submit='<?php echo $this->getAddToCartUrl($_product) ?>'>
                                                <span>
                                                   <span><?php echo $this->__('Add To Cart') ?></span>
                                                </span>
                                                </button>
                                                <?php if (Mage::getStoreConfig('ajaxcart/ajaxcart_config/enable_ajaxcart')) : ?>
                                                <a style="display: none;" href='<?php echo $this->getUrl('ajaxcart/index/options', array_merge($theme->checkSSL(), array('product_id'=>$_product->getId())));?>' class='options-cart' data-id='options-cart-<?php echo $_product->getId()?>'><?php echo $this->__('Option cart')?></a>
                                                <?php endif; ?>

                                            <?php }  ?>
                                        <?php else: ?>
                                            <p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
                                        <?php endif; ?>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="top-actions-inner">
                        <?php echo $this->getReviewsSummaryHtml($_product, 'short') ?>
                        <h3 class="product-name">
                            <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>">
                                <?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?>
                            </a>
                        </h3>
                        <div class="table">
                            <?php echo $this->getPriceHtml($_product, true, '-'.$pricePrefixId) ?>
                        </div>
                    </div>
                </div>
            </div>
        </li>
        <?php if ($i == $count || $i % $column == 0 || ($row > 1 && $i % $row == 0)): ?>
        </ul>
        </div>
    <?php endif ?>
        <?php if ($carousel == 1 && $row > 1 && $i == $count): ?>
            </div>
        <?php endif ?>
    <?php endforeach ?>
<?php endif ?>
