<?php
/**
 * @copyright    Copyright (C) 2015 Skstore. All Rights Reserved.
 */
?>
<?php
$blocks     = $this->getBlocks();
$id         = $this->getConfig('id');
$scroll     = $this->getConfig('scroll');
$title      = $this->getConfig('widget_title');
$layout = $this->getConfig("layout_type");
if ($layout == 'box')	{
	$box = true;
} else {
	$box=false;
}
?>
<?php if ($box) : ?>
<div class="container">
<div class="main-container-inner">
<?php else: ?>
<div class="clearfix">
<?php endif ?>
<div class="<?php echo $this->getConfig('classes') ?>" id="<?php echo $id ?>">
		<div class="block block-sample row clearfix">
		    <?php if ($title): ?>
		    <div class="block-title">
				<strong><span><?php echo $title ?></span></strong>
			</div>
			<?php if ($this->getConfig('widget_description')): ?>
			<div class="widget-description">
				<?php echo $this->getConfig('widget_description');	?>
			</div>
			<?php endif; ?>
			<?php endif ?>
			 <div class="<?php echo $scroll==1 ? 'owl-carousel owl-theme ' : '' ?>">
				<?php foreach ($blocks as $block): ?>
					<div class="<?php echo $scroll==1 ? 'block-content' : $block['class']?>">
						<?php echo $block['content'] ?>
					</div>
				<?php endforeach ?>
			</div>
		</div>
		<?php if ($this->getConfig('widget_custom_html_bottom')): ?>
		<div class="widget-custom-bottom">
			<?php echo $this->getConfig('widget_custom_html_bottom');	?>	
		</div>
	<?php endif; ?>
    <script type="text/javascript" src="<?php echo Mage::getBaseUrl('js') ?>ktmcore/widget/ktmwidget.min.js"></script>
    <script type="text/javascript">
        new Ktm.Widget('<?php echo $id ?>', {
            carousel: <?php echo $this->getConfig('carousel') ?>,
            carouselConfig: null,
            animation: <?php echo $this->getConfig('animation') ?>,
            parallax: <?php echo $this->getConfig('parallax') ?>,
            kenburns: <?php echo $this->getConfig('kenburns') ?>,
            countdown: <?php echo $this->getConfig('countdown') ?>,
            countdownConfig: null,
            countdownTemplate: '<div class="ele day"><span class="num">%d</span><span class="unit">%td</span></div><div class="ele hour"><span class="num">%h</span><span class="unit">%th</span></div><div class="ele minute"><span class="num">%i</span><span class="unit">%ti</span></div><div class="ele second"><span class="num">%s</span><span class="unit">%ts</span></div>',
        });
    </script>
</div>
<?php if ($box) : ?>
</div>
</div>
<?php else: ?>
</div>
<?php endif ?>