<?php 

$brands = $this->getBrands();
$id         = $this->getConfig('id');
$scroll     = $this->getConfig('scroll');
$title      = $this->getConfig('widget_title');
$layout = $this->getConfig("layout_type");
if ($layout == 'box')	{
	$box = true;
} else {
	$box=false;
}
?>
<?php if (count($brands)):	?>
<?php if ($box) : ?>
<div class="container">
<div class="main-container-inner">
<?php else: ?>
<div class="clearfix">
<?php endif ?>
<div class="<?php echo $this->getConfig('classes') ?>" id="<?php echo $id ?>">
    <div class="container">
		<?php if ($title): ?>
			<div class="main-heading">
				<div class="heading-title">
                    <h3><span><?php echo $title ?></span></h3>
				</div>
			</div>
		<?php endif ?>
		<?php if ($this->getConfig('widget_description')): ?>
		<div class="widget-description">
			<?php echo $this->getConfig('widget_description');	?>
		</div>
		<?php endif; ?>
        <ul class="brands-container <?php echo $scroll==1 ? 'owl-carousel ' : '' ?>">
            <?php foreach ($brands as $attribute): ?>
                <li>
                    <?php if ($attribute['link']): ?>
                        <a class="brand-image" href="<?php echo $attribute['link'] ?>" title="<?php echo $attribute['label'] ?>">
                    <?php endif ?>
                    <?php if ($attribute['image']): ?>
                        <?php if ($scroll == 1): ?>
                            <img class="img-responsive" data-src="<?php echo $attribute['image'] ?>" alt="<?php echo $attribute['label'] ?>" src="<?php echo $attribute['image'] ?>" />
						<?php else: ?>
                            <img src="<?php echo $attribute['image'] ?>" alt="<?php echo $attribute['label'] ?>" />
					   <?php endif ?>
                    <?php else: ?>
                       
                    <?php endif ?>
                    <?php if ($attribute['link']): ?>
                        </a>
                    <?php endif ?>
					<?php if ($attribute['link']): ?>
                        <a class="brand-text" href="<?php echo $attribute['link'] ?>" title="<?php echo $attribute['label'] ?>">
						<span class="label-text"><?php echo $attribute['label'] ?></span>
						</a>
                    <?php else: ?>
						<span class="label-text"><?php echo $attribute['label'] ?></span>
                    <?php endif ?>
                </li>
            <?php endforeach ?>
        </ul>
    </div>
	<?php if ($this->getConfig('widget_custom_html_bottom')): ?>
	<div class="widget-custom-bottom">
		<?php echo $this->getConfig('widget_custom_html_bottom');	?>	
	</div>
	<?php endif; ?>
    <script type="text/javascript" src="<?php echo Mage::getBaseUrl('js') ?>ktmcore/widget/ktmwidget.min.js"></script>
    <script type="text/javascript">
        new Ktm.Widget('<?php echo $id ?>', {
            animation: <?php echo $this->getConfig('animation') ?>,
            parallax: <?php echo $this->getConfig('parallax') ?>,
            carousel: <?php echo $this->getConfig('carousel') ?>,
            carouselConfig: null,
            kenburns: <?php echo $this->getConfig('kenburns') ?>
        });
    </script>
</div>
<?php if ($box) : ?>
</div>
</div>
<?php else: ?>
</div>
<?php endif ?>
<?php endif; ?>